@php
    $reportTitle = match($reportType) {
        'reservation' => 'Reservations Report',
        'inventory' => 'Inventory Report',
        'crm' => 'CRM Report',
        default => ucfirst($reportType) . ' Report',
    };
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $reportTitle }} - {{ $startDate->format('M d, Y') }} to {{ $endDate->format('M d, Y') }}</title>
    <style>
        @page { margin-top: 4mm; margin-bottom: 8mm; margin-left: 8mm; margin-right: 8mm; }
        :root {
            --primary: #00462E; --primary-light: #057C3C; --accent: #FF6B35;
            --neutral-50: #fafafa; --neutral-100: #f5f5f5; --neutral-200: #e5e5e5;
            --neutral-300: #d4d4d4; --neutral-400: #a3a3a3; --neutral-500: #737373;
            --neutral-600: #525252; --neutral-700: #404040; --neutral-800: #262626;
            --neutral-900: #171717; --success: #059669;
        }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; margin: 0; padding: 0; color: var(--neutral-800); background: white; }
        .header { text-align: center; border-bottom: 2px solid var(--primary); padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 18px; color: var(--primary); font-weight: 700; }
        .header p { margin: 3px 0; color: var(--neutral-600); font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 11px; border-radius: 6px; overflow: hidden; }
        th, td { border: 0.5px solid var(--neutral-300); padding: 6px 8px; text-align: left; vertical-align: top; }
        th { background-color: var(--primary); color: white; font-weight: 600; font-size: 10px; text-transform: uppercase; }
        tr:nth-child(even) { background-color: var(--neutral-50); }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid var(--neutral-300); text-align: center; font-size: 10px; color: var(--neutral-500); }
        .currency { font-weight: bold; color: var(--success); }
        .no-data { text-align: center; padding: 30px; color: var(--neutral-500); font-style: italic; font-size: 12px; background: var(--neutral-50); border-radius: 6px; border: 1px solid var(--neutral-200); }
        .charts-section { margin-bottom: 14px; page-break-inside: avoid; }
        .charts-title { margin: 0 0 6px 0; font-size: 11px; color: var(--neutral-700); text-transform: uppercase; letter-spacing: 0.04em; font-weight: 700; }
        .charts-grid { width: 100%; border-collapse: collapse; margin: 0; }
        .charts-grid td { border: none; width: 50%; vertical-align: top; padding: 0 5px 8px 0; }
        .diagram-card { border: 1px solid var(--neutral-200); border-radius: 7px; padding: 6px; background: #fff; min-height: 165px; }
        .diagram-card h4 { margin: 0 0 4px 0; font-size: 10px; color: var(--neutral-700); font-weight: 700; }
        .chart-card img { width: 320px; max-width: 100%; height: auto; display: block; margin: 0 auto; }
        .insight-card { min-height: 165px; }
        .insight-list { margin: 0; padding: 0 0 0 14px; }
        .insight-list li { margin: 0 0 4px 0; font-size: 9px; color: var(--neutral-700); line-height: 1.35; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $reportTitle }}</h1>
        <p>Report Period: {{ $startDate->format('F d, Y') }} - {{ $endDate->format('F d, Y') }}</p>
        <p>Generated on: {{ now()->format('F d, Y \a\t H:i') }}</p>
        <p>Generated by: {{ $generatedBy }}</p>
    </div>

    @if(!empty($chartSvgs) || !empty($insights))
        <div class="charts-section">
            <h3 class="charts-title">Charts & Diagrams</h3>
            <table class="charts-grid">
                <tbody>
                    @php
                        $diagramCards = [];
                        foreach (($chartSvgs ?? []) as $chart) {
                            $diagramCards[] = ['type' => 'chart', 'label' => $chart['label'] ?? 'Chart', 'svg' => $chart['svg'] ?? null];
                        }
                        if (!empty($insights)) {
                            $diagramCards[] = ['type' => 'insights', 'label' => 'Summary', 'items' => $insights];
                        }
                        if (($reportType ?? null) === 'inventory') {
                            $lowStockItems = array_map(function ($item) {
                                $name = $item['name'] ?? 'Unknown Item';
                                $stock = number_format((float) ($item['stock_left'] ?? 0), 2);
                                $unit = $item['unit'] ?? 'unit';
                                return "{$name} ({$stock} {$unit})";
                            }, $inventoryLowStockItems ?? []);

                            $outOfStockItems = array_map(function ($item) {
                                $name = $item['name'] ?? 'Unknown Item';
                                $stock = number_format((float) ($item['stock_left'] ?? 0), 2);
                                $unit = $item['unit'] ?? 'unit';
                                return "{$name} ({$stock} {$unit})";
                            }, $inventoryOutOfStockItems ?? []);

                            $diagramCards[] = ['type' => 'insights', 'label' => 'Low Stock / Critical Items', 'items' => !empty($lowStockItems) ? $lowStockItems : ['No low stock items.']];
                            $diagramCards[] = ['type' => 'insights', 'label' => 'Out of Stock Items', 'items' => !empty($outOfStockItems) ? $outOfStockItems : ['No out of stock items.']];
                        }
                        $chartChunks = array_chunk($diagramCards, 2);
                    @endphp
                    @foreach($chartChunks as $chunk)
                        <tr>
                            @foreach($chunk as $card)
                                <td>
                                    @if(($card['type'] ?? '') === 'insights')
                                        <div class="diagram-card insight-card">
                                            <h4>{{ $card['label'] ?? 'Summary' }}</h4>
                                            <ul class="insight-list">
                                                @foreach(($card['items'] ?? []) as $insight) <li>{{ $insight }}</li> @endforeach
                                            </ul>
                                        </div>
                                    @else
                                        <div class="diagram-card chart-card">
                                            <h4>{{ $card['label'] ?? 'Chart' }}</h4>
                                            <img src="{{ $card['svg'] }}" alt="{{ $card['label'] ?? 'Chart' }}">
                                        </div>
                                    @endif
                                </td>
                            @endforeach
                            @if(count($chunk) < 2) <td></td> @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endif

    @if($reportType === 'reservation')
        @if($reservationData->isEmpty())
            <div class="no-data"><p>No reservation data found for the selected period.</p></div>
        @else
            <table>
                <thead>
                    <tr>
                        <th style="width: 8%;">Res. ID</th>
                        <th style="width: 15%;">Event Name</th>
                        <th style="width: 12%;">Event Date</th>
                        <th style="width: 12%;">Customer</th>
                        <th style="width: 10%;">Dept/Office</th>
                        <th style="width: 8%;">Persons</th>
                        <th style="width: 15%;">Expected Revenue</th>
                        <th style="width: 12%;">Status & Payment</th>
                        <th style="width: 8%;">Created</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reservationData as $reservation)
                    <tr>
                        <td>{{ $reservation['id'] }}</td>
                        <td>{{ $reservation['event_name'] }}</td>
                        <td>{{ $reservation['event_date'] }}</td>
                        <td>{{ $reservation['customer_name'] }}</td>
                        <td>{{ $reservation['department'] }}</td>
                        <td style="text-align: center;">{{ $reservation['participants'] }}</td>
                        <td style="text-align: right;" class="currency">PHP {{ number_format($reservation['expected_revenue'], 2) }}</td>
                        {{-- MODIFIED TO SHOW PAYMENT STATUS IN PDF --}}
                        <td>{{ $reservation['status'] }} - {{ $reservation['payment_status'] ?? 'Unpaid' }}</td>
                        <td>{{ $reservation['created_at'] }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
        <div class="footer"><p>This report was generated automatically by the Smart Cafeteria Management System.</p></div>

    @elseif($reportType === 'inventory')
        @if($inventoryData->isEmpty())
            <div class="no-data"><p>No inventory usage data found for the selected period.</p></div>
        @else
            <table>
                <thead>
                    <tr>
                        <th style="width: 50%;">Inventory Item</th>
                        <th style="width: 20%;">Unit</th>
                        <th style="width: 30%;">Current Stock Left</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($inventoryData as $item)
                    <tr>
                        <td>{{ $item['name'] }}</td>
                        <td>{{ $item['unit'] }}</td>
                        <td style="text-align: right;">{{ number_format($item['stock_left'], 2) }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
        <div class="footer"><p>This report was generated automatically by the Smart Cafeteria Management System.</p><p>Report covers current snapshot of stock left.</p></div>

    @elseif($reportType === 'crm')
        @if($crmData->isEmpty())
            <div class="no-data"><p>No customer data found for the selected period.</p></div>
        @else
            <table>
                <thead>
                    <tr>
                        <th style="width: 25%;">Customer Name</th>
                        <th style="width: 25%;">Email</th>
                        <th style="width: 10%;">Total Reservations</th>
                        <th style="width: 15%;">Approved</th>
                        <th style="width: 15%;">Total Spent</th>
                        <th style="width: 10%;">Last Reservation</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($crmData as $customer)
                    <tr>
                        <td>{{ $customer['name'] }}</td>
                        <td>{{ $customer['email'] }}</td>
                        <td style="text-align: center;">{{ $customer['total_reservations'] }}</td>
                        <td style="text-align: center;">{{ $customer['approved_reservations'] }}</td>
                        <td style="text-align: right;" class="currency">PHP {{ number_format($customer['total_spent'], 2) }}</td>
                        <td>{{ $customer['last_reservation'] }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
        <div class="footer"><p>This report was generated automatically by the Smart Cafeteria Management System.</p><p>Report covers customers with reservations in the selected period.</p></div>
    @endif
    <script type="text/php">
        if (isset($pdf)) {
            $font = $fontMetrics->get_font('DejaVu Sans', 'normal');
            $size = 9;
            $text = 'Page {PAGE_NUM} of {PAGE_COUNT}';
            $y = $pdf->get_height() - 24;
            $x = $pdf->get_width() - $fontMetrics->get_text_width($text, $font, $size) - 18;
            $pdf->page_text($x, $y, $text, $font, $size, [0.45, 0.45, 0.45]);
        }
    </script>
</body>
</html>
