<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reservations Export</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #1f2937;
            margin: 24px;
        }

        h1 {
            margin: 0 0 6px;
            font-size: 20px;
        }

        p {
            margin: 0 0 4px;
        }

        .meta {
            margin-bottom: 18px;
        }

        .summary {
            margin-bottom: 16px;
            padding: 10px 12px;
            border: 1px solid #d1d5db;
            border-radius: 8px;
            background: #f9fafb;
        }

        .summary-row {
            margin-bottom: 4px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #d1d5db;
            padding: 8px 7px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #f3f4f6;
            font-size: 10px;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }

        .muted {
            color: #6b7280;
        }
    </style>
</head>
<body>
    <h1>Reservations</h1>
    <div class="meta">
        <p>Generated by: {{ $exportedBy ?? 'Unknown' }}</p>
        <p>Generated at: {{ optional($exportedAt)->format('Y-m-d H:i') ?? now()->format('Y-m-d H:i') }}</p>
    </div>

    <div class="summary">
        <div class="summary-row"><strong>Total Records:</strong> {{ $reservations->count() }}</div>
        <div class="summary-row">
            <strong>Created Date Range:</strong>
            {{ ($createdFrom || $createdTo) ? (($createdFrom ?: 'Any') . ' to ' . ($createdTo ?: 'Any')) : 'All Dates' }}
        </div>
        <div class="summary-row"><strong>Status Filter:</strong> {{ $status ? ucfirst($status) : 'All Status' }}</div>
        <div class="summary-row"><strong>Payment Filter:</strong> {{ $payment ? ucfirst($payment) : 'All Types' }}</div>
        <div class="summary-row"><strong>Office/Dept Filter:</strong> {{ $department ?: 'All Office/Dept' }}</div>
        <div class="summary-row"><strong>Created Sort:</strong> {{ strtoupper($createdSort ?? 'desc') }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Customer</th>
                <th>Department/Office</th>
                <th>Status</th>
                <th>Payment</th>
                <th>Created</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reservations as $reservation)
                @php
                    $statusValue = strtolower((string) ($reservation->status ?? 'pending'));
                    $statusLabel = match ($statusValue) {
                        'approved' => 'Approved',
                        'declined' => 'Declined',
                        'cancelled' => 'Cancelled',
                        default => 'Pending',
                    };

                    $paymentLabel = in_array($statusValue, ['declined', 'cancelled'], true)
                        ? 'N/A'
                        : (($reservation->payment_status ?? 'unpaid') === 'paid' ? 'Paid' : 'Unpaid');
                @endphp
                <tr>
                    <td>{{ $reservation->id }}</td>
                    <td>{{ $reservation->contact_person ?? optional($reservation->user)->name ?? '-' }}</td>
                    <td>{{ $reservation->department ?? optional($reservation->user)->department ?? 'N/A' }}</td>
                    <td>{{ $statusLabel }}</td>
                    <td>{{ $paymentLabel }}</td>
                    <td>{{ optional($reservation->created_at)->format('Y-m-d H:i') ?? 'N/A' }}</td>
                    <td>{{ $reservation->email ?? optional($reservation->user)->email ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" class="muted">No reservations matched the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
